import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import esbuildSvelte from "esbuild-svelte";
import sveltePreprocess from "svelte-preprocess";
import { replace } from "esbuild-plugin-replace";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";

// Custom plugin to log warnings
const logWarningsPlugin = {
  name: 'log-warnings',
  setup(build) {
    build.onEnd(result => {
      if (result.warnings.length > 0) {
        console.warn(`\n⚠️  Build completed with ${result.warnings.length} warning(s):`);
        result.warnings.forEach((warning, i) => {
          console.warn(`  ${i + 1}. ${warning.text}`);
          if (warning.location) {
            console.warn(`     at ${warning.location.file}:${warning.location.line}:${warning.location.column}`);
          }
        });
      }
      if (result.errors.length === 0) {
        console.log(`\n✅ Build successful${prod ? ' (production)' : ' (development)'}`);
      }
    });
  }
};

const buildOptions = {
  plugins: [
    esbuildSvelte({
      compilerOptions: {
        css: true,
        dev: !prod
      },
      preprocess: sveltePreprocess(),
    }),
    replace({
      include: /svelte-dnd-action.*$/,
      delimiters: ["", ""],
      values: {
        "window.": `activeWindow.`,
        "document.": `activeDocument.`,
      },
    }),
    logWarningsPlugin,
  ],
  banner: {
    js: banner,
  },
  entryPoints: ["./src/main.ts"],
  bundle: true,
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/closebrackets",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/comment",
    "@codemirror/fold",
    "@codemirror/gutter",
    "@codemirror/highlight",
    "@codemirror/history",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/matchbrackets",
    "@codemirror/panel",
    "@codemirror/rangeset",
    "@codemirror/rectangular-selection",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/stream-parser",
    "@codemirror/text",
    "@codemirror/tooltip",
    "@codemirror/view",
    ...builtins,
  ],
  format: "cjs",
  target: "es2016",
  logLevel: "info",
  sourcemap: prod ? false : "inline",
  treeShaking: true,
  minify: prod,
  minifyWhitespace: prod,
  minifyIdentifiers: prod,
  minifySyntax: prod,
  outfile: "main.js",
};

if (prod) {
  esbuild.build(buildOptions).catch(() => process.exit(1));
} else {
  esbuild.context(buildOptions).then(ctx => {
    ctx.watch();
  }).catch(() => process.exit(1));
}
